/**
 * template.js — emit a TypeScript file that conforms to AssPresetDefinition.
 * The shape matches packages/engine-ass/src/presets/* hand-written presets:
 *   - import types + hexToAss
 *   - export const buildXxxPreset: AssPresetBuilder = (...) => ({ style, wordTag })
 *   - export const definition: AssPresetDefinition = { slug, tier, description, build }
 *
 * Output is plain text, ready to drop into packs/premium/ (or basic/).
 */

function hexToAssLiteral(hex) {
  const cleaned = hex.replace('#', '').toUpperCase();
  if (cleaned.length !== 6) return '&H00000000&';
  const rr = cleaned.slice(0, 2);
  const gg = cleaned.slice(2, 4);
  const bb = cleaned.slice(4, 6);
  return `&H00${bb}${gg}${rr}&`;
}

function builderFnName(slug) {
  // my-cool-style → buildMyCoolStylePreset
  const camel = slug.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  return 'build' + camel.charAt(0).toUpperCase() + camel.slice(1) + 'Preset';
}

function buildActiveTag(state) {
  const parts = [];
  // Fill colour
  if (state.activeFillDark) {
    parts.push('\\\\c&H000000&');
  } else if (state.highlightColor !== state.fontColor) {
    parts.push(`\\\\c\${hexToAss(highlightColor)}\``.replace(/`/g, ''));
    // The above is awkward — render template literally instead:
  }
  // Outline width override
  if (state.activeBord && Number(state.activeBord) !== Number(state.outlineWidth)) {
    parts.push(`\\\\bord${state.activeBord}`);
  }
  // Outline colour swap to highlight
  if (state.activeOutlineHighlight) {
    parts.push('\\\\3c${hexToAss(highlightColor)}');
  }
  // Scale
  if (state.activeScale && Number(state.activeScale) !== 100) {
    parts.push(`\\\\fscx${state.activeScale}\\\\fscy${state.activeScale}`);
  }
  // Underline
  if (state.activeUnderline) {
    parts.push('\\\\u1');
  }
  return parts.join('');
}

function buildTs(state) {
  const fnName = builderFnName(state.slug);
  const tier = state.tier;
  const transformLine = state.transform !== 'none'
    ? `\n    transformText: (t) => t.to${state.transform === 'uppercase' ? 'UpperCase' : 'LowerCase'}(),`
    : '';

  // Compose the active wordTag body as a real template literal expression.
  // We splice in `${hexToAss(...)}` calls only where the user picked a colour.
  const activeBits = [];
  if (state.activeFillDark) activeBits.push('\\\\c&H000000&');
  else activeBits.push('\\\\c${hexToAss(highlightColor)}');
  if (state.activeBord && Number(state.activeBord) !== Number(state.outlineWidth)) activeBits.push(`\\\\bord${state.activeBord}`);
  if (state.activeOutlineHighlight) activeBits.push('\\\\3c${hexToAss(highlightColor)}');
  if (state.activeScale && Number(state.activeScale) !== 100) activeBits.push(`\\\\fscx${state.activeScale}\\\\fscy${state.activeScale}`);
  if (state.activeUnderline) activeBits.push('\\\\u1');
  const activeTag = '`{' + activeBits.join('') + '}`';

  // Past explicit reset only required when active changes \bord (renderer
  // doesn't auto-invert that). For all other tags the renderer infers it.
  const needsExplicitPast = state.activeBord && Number(state.activeBord) !== Number(state.outlineWidth);
  const pastBlock = needsExplicitPast
    ? `\n      if (state === 'past') return \`{\\\\bord${state.outlineWidth}\\\\3c\${hexToAss(outlineColor)}\\\\c\${hexToAss(fontColor)}}\`;`
    : '';

  return `/**
 * ${state.slug} — ${state.description}
 *
 * Generated by captions-cli studio designer.
 * Drop into packs/${tier}/ then run scripts/install-pack.sh ${tier}.
 */
import type { AssPresetBuilder, AssPresetDefinition } from '../types';
import { hexToAss } from '../ass-helpers';

export const ${fnName}: AssPresetBuilder = ({
  fontColor,
  fontSize,
  highlightColor,
  upcomingColor,
}) => {
  const upcoming = upcomingColor ?? fontColor;
  const outlineColor = '${state.outlineColor}';
  return {
    style: [
      'Default',
      'Inter',
      String(fontSize),
      hexToAss(fontColor),                       // PrimaryColour
      hexToAss(fontColor),                       // SecondaryColour
      hexToAss(outlineColor),                    // OutlineColour
      '&H80000000',                              // BackColour
      '${state.bold}', '${state.italic}', '0', '0',  // Bold, Italic, Underline, StrikeOut
      '100', '100',                              // ScaleX, ScaleY
      '${state.spacing}', '0',                   // Spacing, Angle
      '${state.borderStyle}',                    // BorderStyle
      '${state.outlineWidth}',                   // Outline
      '${state.shadowDepth}',                    // Shadow
      '2', '40', '40', '400', '1',
    ].join(','),
    wordTag(state) {
      if (state === 'active') return ${activeTag};
      if (state === 'upcoming') return \`{\\\\c\${hexToAss(upcoming)}}\`;${pastBlock}
      return '';
    },${transformLine}
  };
};

export const definition: AssPresetDefinition = {
  slug: '${state.slug}',
  tier: '${tier}',
  description: '${state.description.replace(/'/g, "\\'")}',
  build: ${fnName},
};
`;
}

window.template = { buildTs };
