/**
 * AUTO-GENERATED by scripts/generate-presets-index.mjs.
 * Do not edit by hand. Re-run after copying pack files into this dir.
 *
 * Order: free → basic → premium → (alphabetical within tier).
 */
import type { HfPresetBuilder, HfPresetDefinition, HfPresetTier } from '../types';

import { definition as text } from './text';
import { definition as boxHighlight } from './box-highlight';
import { definition as pill } from './pill';
import { definition as glow } from './glow';
import { definition as hormozi } from './hormozi';
import { definition as hype } from './hype';
import { definition as outlinePop } from './outline-pop';
import { definition as paperCutout } from './paper-cutout';
import { definition as paperCutoutTyped } from './paper-cutout-typed';
import { definition as popWord } from './pop-word';
import { definition as singleWord } from './single-word';
import { definition as underlineSweep } from './underline-sweep';

export const DEFINITIONS: HfPresetDefinition[] = [
  text,  // free
  boxHighlight,  // basic
  pill,  // basic
  glow,  // premium
  hormozi,  // premium
  hype,  // premium
  outlinePop,  // premium
  paperCutout,  // premium
  paperCutoutTyped,  // premium
  popWord,  // premium
  singleWord,  // premium
  underlineSweep,  // premium
];

export const PRESETS: Record<string, HfPresetBuilder> = Object.fromEntries(
  DEFINITIONS.map((d) => [d.slug, d.build]),
);

export const PRESET_DESCRIPTIONS: Record<string, string> = Object.fromEntries(
  DEFINITIONS.map((d) => [d.slug, d.description]),
);

export function tierForPreset(slug: string): HfPresetTier {
  return DEFINITIONS.find((d) => d.slug === slug)?.tier ?? 'free';
}

export function listPresets(): string[] {
  return DEFINITIONS.map((d) => d.slug);
}

export function presetsByTier(): Record<HfPresetTier, HfPresetDefinition[]> {
  const out: Record<HfPresetTier, HfPresetDefinition[]> = {
    free: [],
    basic: [],
    premium: [],
  };
  for (const d of DEFINITIONS) out[d.tier].push(d);
  return out;
}
