/**
 * AUTO-GENERATED by scripts/generate-presets-index.mjs.
 * Do not edit by hand. Re-run after copying pack files into this dir.
 *
 * Order: free → basic → premium → (alphabetical within tier).
 */
import type { HfPresetBuilder, HfPresetDefinition, HfPresetTier } from '../types';

import { definition as text } from './text';

export const DEFINITIONS: HfPresetDefinition[] = [
  text,  // free
];

export const PRESETS: Record<string, HfPresetBuilder> = Object.fromEntries(
  DEFINITIONS.map((d) => [d.slug, d.build]),
);

export const PRESET_DESCRIPTIONS: Record<string, string> = Object.fromEntries(
  DEFINITIONS.map((d) => [d.slug, d.description]),
);

export function tierForPreset(slug: string): HfPresetTier {
  return DEFINITIONS.find((d) => d.slug === slug)?.tier ?? 'free';
}

export function listPresets(): string[] {
  return DEFINITIONS.map((d) => d.slug);
}

export function presetsByTier(): Record<HfPresetTier, HfPresetDefinition[]> {
  const out: Record<HfPresetTier, HfPresetDefinition[]> = {
    free: [],
    basic: [],
    premium: [],
  };
  for (const d of DEFINITIONS) out[d.tier].push(d);
  return out;
}
