/**
 * AUTO-GENERATED by scripts/generate-presets-index.mjs.
 * Do not edit by hand. Re-run after copying pack files into this dir.
 *
 * Order: free → basic → premium → (alphabetical within tier).
 */
import type { AssPresetBuilder, AssPresetDefinition, AssPresetTier } from '../types';

import { definition as cleanWhite } from './clean-white';

export const DEFINITIONS: AssPresetDefinition[] = [
  cleanWhite,  // free
];

export const PRESETS: Record<string, AssPresetBuilder> = Object.fromEntries(
  DEFINITIONS.map((d) => [d.slug, d.build]),
);

export const PRESET_DESCRIPTIONS: Record<string, string> = Object.fromEntries(
  DEFINITIONS.map((d) => [d.slug, d.description]),
);

export function tierForPreset(slug: string): AssPresetTier {
  return DEFINITIONS.find((d) => d.slug === slug)?.tier ?? 'free';
}

export function listPresets(): string[] {
  return DEFINITIONS.map((d) => d.slug);
}

export function presetsByTier(): Record<AssPresetTier, AssPresetDefinition[]> {
  const out: Record<AssPresetTier, AssPresetDefinition[]> = {
    free: [],
    basic: [],
    premium: [],
  };
  for (const d of DEFINITIONS) out[d.tier].push(d);
  return out;
}
